/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prova;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Oscar
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chrono Schedule 1.0");
        setMinimumSize(new java.awt.Dimension(778, 444));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018", "2019", "2020" }));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        createCalendar(jPanel2, jPanel1);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        createCalendar(jPanel2, jPanel1);
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        createCalendar(jPanel2, jPanel1);
        
    }//GEN-LAST:event_formWindowOpened

    public void createCalendar (JPanel jPanelYearMonth, JPanel jPanelDays) {
        
        jPanelYearMonth.setLayout(new GridLayout(1,2));
        JComboBox jComboBoxYear = new JComboBox();
        Calendar c1 = Calendar.getInstance();
        int currentYear = c1.get(Calendar.YEAR);
        for (int i = 0; i <= 6; i++) {
            jComboBoxYear.addItem(String.valueOf(currentYear + i));
        }
        jPanelYearMonth.add(jComboBoxYear);
        
        
        JComboBox jComboBoxMonth = new JComboBox();
        for (int i = 0; i < Constants.MONTH_NAME.length; i++) {
            jComboBoxMonth.addItem(Constants.MONTH_NAME[i]);
        }
        jPanelYearMonth.add(jComboBoxMonth);
        
        
        int year = Integer.valueOf((String)jComboBoxYear.getSelectedItem());
        int month = jComboBoxMonth.getSelectedIndex();
        
        
        
        
        
        
        
        jPanelDays.setLayout(new GridLayout(7,7)); //(filas, columnas)
        jPanelDays.removeAll();
        
        Border border = LineBorder.createGrayLineBorder();
        
        
        //Mostrar los nombres de los días de la semana
        JLabel[] lab = new JLabel[7];
        for (int i = 0; i < lab.length; i++) {
            lab[i] = new JLabel(Constants.DAY_NAME[i], SwingConstants.CENTER);
            lab[i].setForeground(Color.white);
            JPanel titlePanel = new JPanel(new BorderLayout());
            titlePanel.setBackground(Color.black);
            titlePanel.add(lab[i]);  // adds to center of panel's default BorderLayout.
            jPanelDays.add(titlePanel);
        }
        
        
        
        
        
        // Create a calendar object and set year and month
        Calendar mycal = new GregorianCalendar(year, month, 1);
                
        
        
        
        int daysBeforeMonth = getDaysBeforeMonth(mycal);
        Calendar c = new GregorianCalendar(year, month - 1, 1);
        int daysMonthAgo = c.getActualMaximum(Calendar.DAY_OF_MONTH);
        JLabel[] jLab = new JLabel[daysBeforeMonth];
        for (int i = 0; i < daysBeforeMonth; i++) {
            jLab[i] = new JLabel(String.valueOf(daysMonthAgo - daysBeforeMonth + i + 1), SwingConstants.CENTER);
            jLab[i].setForeground(Color.gray);
            jLab[i].setBorder(border);
            jPanelDays.add(jLab[i]);
        }
        
        
        
        
        
        // Get the number of days in that month
        int daysOfMonth = mycal.getActualMaximum(Calendar.DAY_OF_MONTH);
        JLabel[] labels = new JLabel[daysOfMonth];
        for (int i = 0; i < labels.length; i++) { 
            labels[i] = new JLabel(String.valueOf(i + 1), SwingConstants.CENTER);
            labels[i].setBorder(border);
            boldFont(labels[i]);
            jPanelDays.add(labels[i]);
        }
        
        
        
        
        
        JLabel[] jLab2 = new JLabel[42 - daysOfMonth - daysBeforeMonth];
        for (int i = 0; i < jLab2.length; i++) {
            jLab2[i] = new JLabel(String.valueOf(i + 1), SwingConstants.CENTER);
            jLab2[i].setForeground(Color.gray);
            jLab2[i].setBorder(border);
            jPanelDays.add(jLab2[i]);
        }
        
        
        jPanelDays.updateUI();
        
        
    }
    
    public static int getDaysBeforeMonth(Calendar cal){
	
        int initialDayOfMonth = cal.get(Calendar.DAY_OF_WEEK);
        
        cal.setMinimalDaysInFirstWeek(7);
        int numberWeekOfMonth = cal.get(Calendar.WEEK_OF_MONTH);
        
        if (numberWeekOfMonth == 0) {
            
            switch (initialDayOfMonth) {
                case 1: return 6;
                default: return initialDayOfMonth - 2;
            }
        
        } else {
            return 7;
        }
      
    } 
    
    public JLabel boldFont (JLabel lab) {
        Font f = lab.getFont();
        lab.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        return lab;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewJFrame1();
                NewJFrame1 jframe = new NewJFrame1();
                jframe.setVisible(true);
                jframe.setLayout(null); //Para colocar los componentes en cualquier ubicación
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
